select * from customer ;

-- Q.1)what is the total revenue generated by male vs. female customers?

SELECT gender , sum(purchase_amount) as revenue
FROM customer
GROUP BY gender;

-- Q.2) which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id , purchase_amount
FROM customer 
WHERE 
      discount_applied = 'Yes' and 
      purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q.3)which are the top 5 products with the highest average review rating ?

SELECT item_purchased , ROUND(AVG(review_rating::numeric),2) AS Average_product_rating
FROM customer
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

-- Q.4)Compare the average purchase amount between standard and express shipping
SELECT shipping_type , 
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE 
     shipping_type in ('Standard','Express')
GROUP BY 1;

-- Q.5)Do subscribed customers spend more ? Compare average spend and total revenue 
-- between subscribers and non- subscriber.

SELECT subscription_status , 
COUNT(customer_id ) as total_customer ,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend;

-- Q.6) which 5 products have the higest percentage of purchases with discount applied
SELECT item_purchased ,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) ,2) as discount_rate
FROM customer
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;


-- Q.7)Segment customers into new , returning , and loyal based on their total 
-- number of previous purchases , and show the count of each segment .
WITH customer_type AS
(
SELECT customer_id , previous_purchases,
CASE WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	 ELSE 'Loyal'
	 END AS customer_segment 
FROM customer
)

SELECT customer_segment , COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- Q.7)what are the top 3 most purchased products within each category ? 
WITH item_counts as
(
SELECT category ,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category order by count(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category , item_purchased 
) 
SELECT item_rank , category , item_purchased , total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q.9) Are customers who are repeat buyers (more than 5 previous purchases) also likely 
-- to subscribe?

SELECT subscription_status ,
COUNT(customer_id) as repeat_buyers 
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status ;


-- Q.10) what is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue 
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC ;





